# Generated by Django 4.0.1 on 2022-01-10 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Alert_Name', models.FileField(max_length=50, upload_to='', verbose_name='Имя админа')),
                ('Alert_TelegramAddress', models.FileField(max_length=200, upload_to='', verbose_name='Telegram адрес')),
                ('Alert_Activity', models.BooleanField(verbose_name='Активность')),
                ('Alert_DateAdded', models.DateTimeField(verbose_name='Дата добавления')),
                ('Alert_EditingDate', models.DateTimeField(verbose_name='Дата редактирования')),
            ],
        ),
        migrations.CreateModel(
            name='PointData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PointData_Name', models.FileField(max_length=50, upload_to='', verbose_name='Название точки')),
                ('PointData_IP', models.FileField(max_length=15, upload_to='', verbose_name='IP')),
                ('PointData_Availability', models.BooleanField(verbose_name='Доступность')),
                ('PointData_TestingIncluded', models.BooleanField(verbose_name='Тестирование включено')),
                ('PointData_DateAdded', models.DateTimeField(verbose_name='Дата добавления')),
            ],
        ),
        migrations.CreateModel(
            name='LogOfSendingNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LogOfSendingNotifications_Date', models.DateTimeField(verbose_name='Дата оповещения')),
                ('LogOfSendingNotifications_SubmissionStatus', models.TextField(verbose_name='Дата оповещения')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testlanapp.alert')),
            ],
        ),
        migrations.CreateModel(
            name='CheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CheckLog_ResponseTime', models.IntegerField(default=0, verbose_name='Время ответа')),
                ('CheckLog_NumberOfJumpsToPoint', models.IntegerField(default=0, verbose_name='Количество прыжков до точки')),
                ('CheckLog_TestDate', models.DateTimeField(verbose_name='Дата теста')),
                ('pointdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testlanapp.pointdata')),
            ],
        ),
    ]
