# Generated by Django 4.0.1 on 2022-01-11 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testlanapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'verbose_name': 'Даннае пользователей для оповещения'},
        ),
        migrations.AlterModelOptions(
            name='pointdata',
            options={'verbose_name': 'Список тестируемых устройств'},
        ),
        migrations.RemoveField(
            model_name='alert',
            name='Alert_DateAdded',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='Alert_EditingDate',
        ),
        migrations.RemoveField(
            model_name='pointdata',
            name='PointData_DateAdded',
        ),
    ]
