# Generated by Django 4.0.1 on 2022-01-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testlanapp', '0002_alter_alert_options_alter_pointdata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='Alert_TelegramAddress',
            field=models.URLField(verbose_name='Telegram адрес'),
        ),
    ]
